### ISSUE TITLE
Text block editor has a resize handle

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-android#1097]
Strangely enough, the resize handle actually works, but

a) that's not an affordance that mobile users will understand
b) the resize handle is way too small.

Suggest we just make the text box not really resizable by hand. (It should grow with large text bodies though).

**Comment by gesa** [comment]
There are a couple ways to do this

1. Using css and javascript to dynamically resize the element, which is good but can get complicated
2. Changing our `<textarea>` to a `<div contenteditable>` which will dynamically resize (from there we can use a line or two of js to grab the text and put it where ever we need it)

Curious if you have strong opinions on either of these @k88hudson @gvn @Pomax @alicoding

**Comment by gvn** [comment]
I think `contenteditable` would be easier to work with CSS-wise.

**Comment by davidascher** [comment]
The use case that I think is important is, based on experiences others have had with mobile authoring apps, is people will want to create large texts, and editing large texts through a two-line editor is painful. I'm agnostic is as to how we support those use cases.

**Comment by k88hudson** [comment]
Makes sense @davidascher, especially for long-form editing.

Unfortunately I don't think `contenteditable` is a viable option here since there are too many issues with unexpected browser behaviour/rich text copying/etc. 

Perhaps we could do something like this (sorry for the janky in-browser hack):
![image](https://cloud.githubusercontent.com/assets/1455535/6238721/8294cd30-b6cb-11e4-805b-53e2230d6591.png)

**Comment by k88hudson** [comment]
@vazquez what are your thoughts on this

**Comment by k88hudson** [comment]
Also, this would be a fairly substantial change, so we might want to consider pushing til after MWC.

**Comment by davidascher** [comment]
FYI, don't care if this happens before or after MWC.
