### ISSUE TITLE
Implement git-flow style branching standard

### ISSUE THREAD

**Issue by simonwex** [mozilla/webmaker-android#1223]
Reference this issue for discussion:
https://github.com/MozillaFoundation/MoFo-Engineering-Handbook/issues/47

**Comment by k88hudson** [comment]
I would vote to do this after merging webmaker-app and webmaker-app-cordova, since there a lot of subsequent updates that need to be made.

When we do this, let's make sure we also:

* update necessary documentation
* add "hotfix" documentation
* send out communication where possible to help contributors adjust workflow, and help contributors rebase their PRs against the new dev branch
* switch the default branch in github to be dev (note that this is a github-only convention, this concept does not exist in git – so we may also need to help people adjust their git commands, and expect that people will do it wrong sometimes)
* update any githooks or bots that reference master where needed
* update travis to use the dev branch for nightly builds in all repos.

These are just off the top of my head, feel free to add more.

**Comment by thisandagain** [comment]
We should do this when we are ready to blow up the MWC version (alpha release).

**Comment by thisandagain** [comment]
Done! :boom: :fork_and_knife:

**Comment by k88hudson** [comment]
:+1:
