### ISSUE TITLE
Elements - Define defaults

### ISSUE THREAD

**Issue by scootergrisen** [mozilla/webmaker-android#1227]
The static/images/blocks_image.png used when adding content dont really indicate an image.
Its just a circle in a rounded square.

Then when you select to add an image you see the placeholder.png image which looks more like an image.

And then if you select the image and select the pencil you yet another version of the two icons.
So i guess there is an option for taking pictures with the camera.

**Comment by thisandagain** [comment]
:+1: Agreed!

**Comment by thisandagain** [comment]
@vazquez @flukeout @xmatthewx This is something to think about for beta ... before a user selects an image, what should we show?

**Comment by flukeout** [comment]
Here's a stab at options & defaults. In general, I think we should randomize certain properties when it makes sense.

**Text**
* Copy - Prompting for the copy initially makes sense. Alternatively, we could pick from a list of phrases like translations of "Hello".
* Font-Size - *Randomize from smaller range than available options*
* Font Family - *Randomize from available options*
* Font Color - *Randomize from available options*

**Image**
* Border Color - *Randomize from available options*
* Border Thickness - *Randomize from available options*
* Transparency - *Randomize from available options*
* Source -

**Comment by xmatthewx** [comment]
@flukeout - yes, let's revisit the list and check it against the build. 

I like the idea of randomizing on first use within a project as you've detailed. I think that after that, it should default to last used style. Adding a bunch of images will get annoying, for example, if you need to specify border every time. I like randomness on a new project to introduce possibilities. 

Since you can't tap to edit text within the page view, I think 'Hello' would be better than a prompt. I like your random translation idea. 

For images, maybe a set to randomize? Maybe some landscapes or something people might actually use?

I've been thinking we should add background color to text in v1.02. That will make it easier to use with photos. This would need an explicit `none` option.

**Comment by flukeout** [comment]
@xmatthewx Yeah good point, would get annoying to reset stuff. Maybe we should build in 'shuffle mode' to the properties soon then. 

Should we go over this tomorrow morning and form the final spec?

**Comment by flukeout** [comment]
**Page**
* **Background Color** - Same as most recently set page background color on another page. If starting a brand new project, then first auto-created page has a random background color

**Text**
* **Copy** - Prompting for the copy initially makes sense. Alternatively, we could pick from a list of phrases like translations of "Hello".
* **Font-Size** - Randomize from smaller range than available options
* **Font Family** - Randomize from available options
* **Text Alignment** - Center  <- We should revisit the Text element, the UX in the build doesn't match our previous notions.
* **Text Color** - Randomize from available options
* **Background Color** - Transparent

**Button**
* **Label** - "Tap me" or alternatively, we could pick from a list of phrases like translations of "Tap".
* **Font Family** - Randomize from available options
* **Roundness** (border-radius) - Randomize from smaller range than available options
* **Text Color** - White
* **Background Color** - Randomize from available options

**Image**
* Border Color - *Randomize from available options*
* Border Thickness - *Randomize from available options*
* Transparency - *Randomize from available options*
* Source - *Picture of the Toucan, but with a background color*
* Roundness (border-radius) - *Randomize from smaller range than available options*

**Comment by flukeout** [comment]
**Round 2**
Let's run with a specific set of defaults instead of "always-random".

**Page**
* **Background Color** - Random color if first page of a new project. If adding second page, default is last-set page background color.


**Text**
* **Copy** - Random translation of "Hello".
* **Font-Size** - 18px
* **Font Family** - First choice in the font dropdown, whatever that is
* **Text Alignment** - Center
* **Text Color** - Black
* **Background Color** - None

**Button**
* **Label** - "Tap me"
* **Font Family** - First choice in the font dropdown, whatever that is
* **Roundness** (border-radius) - 3px (are we doing percent?)
* **Text Color** - White
* **Background Color** - Blue

**Image**
* Border Color - None
* Border Thickness - 0px
* Transparency - Not transparent
* Source - Random photo from set of default photos
* Roundness (border-radius) - 0px

**Comment by xmatthewx** [comment]
Looks good. Clear and simple. 
 - Default text color: maybe something bright so it works on photos? fuschia? 
 - Photo border: white border? couple pixels.

Implementation
 - Once I select a style, re-use that for future elements. 
 - Hide border width until color is selected

Questions
 - Add text --> go directly to edit view?? with keyboard??

**Comment by flukeout** [comment]
Added some thoughts about the Text Element UX in #1707

**Comment by flukeout** [comment]
@xmatthewx Should we break these up into separate tickets for each element and finalize?

**Comment by flukeout** [comment]
@xmatthewx I've cleaned up this ticket and the list above reflects what we've agreed upon. There is a big discrepancy between this list and what is currently happening in the app. How would you like to proceed with this list? Want me to break them up into separate issues?

**Comment by xmatthewx** [comment]
@flukeout - I can file these tickets. The one thing I'd like to change is "Tap me" since a button isn't tappable in the editor (#1860). I'm thinking "Button link".

**Comment by flukeout** [comment]
@xmatthewx Sounds good - can you CC me on them when you file them?

**Comment by flukeout** [comment]
@xmatthewx Closing since you created separate tickets for all the elements now.
