### ISSUE TITLE
[MIGRATED] Implement - Choose page background color

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1541]
depends on #1532

**Comment by xmatthewx** [comment]
We need to examine what swatches made in tinker mode will look like, and how they'll behave when there's none, one, some.

**Comment by xmatthewx** [comment]
UX in [build deck](https://docs.google.com/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.gae931fbd6_7_0)

**Comment by vazquez** [comment]
Leave UI Feedback: http://invis.io/BK2M18Q28

![page background color](https://cloud.githubusercontent.com/assets/1119821/7349300/ffda2ac6-ecc5-11e4-9616-83da6411a98f.png)

![page color tinker mode](https://cloud.githubusercontent.com/assets/1119821/7349302/ffdc38de-ecc5-11e4-99cd-77eba7a396df.png)

![page background color changed](https://cloud.githubusercontent.com/assets/1119821/7349301/ffda57bc-ecc5-11e4-8734-73f7ac49f590.png)

**Comment by xmatthewx** [comment]
+1

**Comment by vazquez** [comment]
:boom: Closing.

**Comment by vazquez** [comment]
### Design Documentation

*Scenario:* While in the Page View, user taps on the Page Background icon.

![screenshot 2015-05-04 15 12 22](https://cloud.githubusercontent.com/assets/1119821/7463647/ff8ad390-f26f-11e4-8d53-a2b5ce867736.png)

##### Page Background Screen

The UI will change a little bit:

1. Neighbouring tiles are removed out of view.
2. Main buttons slide down.
3. Colour selection bar slides up

###### Notes

- The colour selection bars behaves the same way as in the Colour Options or Text Options screen. That is, we show a small circle inside of the selected colour.

![page background color](https://cloud.githubusercontent.com/assets/1119821/7463724/b625c164-f270-11e4-988e-adcbd6209408.png)


---

##### Page Background Tinker Mode

- If the user taps on the purple button :zap:, they will enter Tinker Mode. This Tinker Mode experience is the same as any other colour Tinker Mode.

###### Notes

- What is important to note is that once the user creates a new colour in Tinker Mode, we must save this colour and display it on the Page Background Screen.

![page color tinker mode](https://cloud.githubusercontent.com/assets/1119821/7463825/a08d8afc-f271-11e4-9b05-e0b56512c5e4.png)

---

##### Page Background Screen With New Colour

- The Page Background Screen now displays two rows of colour, with the newly created colour selected.
- We will show empty colour swatches if the user has less than 6 custom colours. You can view the empty colour swatch treatment below:

![page background color changed](https://cloud.githubusercontent.com/assets/1119821/7463833/bf0cad14-f271-11e4-83ff-73e06c2d480d.png)

**Comment by flukeout** [comment]
@vazquez @xmatthewx  Let's use this issue for implementation instead of #1702 - this one is more thorough.


**Needed Updates**
* Put "Page Background Color" as the header title instead of the name of the project
* Update how this view is reached (from the map view via the new 'page background' icon)
* Include a sample element on the Page being edited to show that it's a preview of the tile with content, not just the Page by itself

**Questiona about UX**
* When changing the background from the map view, I'd like to zoom in on the so it fills up the page, then zoom back out when the user has finished. Is this doable?
* Should we persist the edge tiles in this view for consistency in the Page Editor?
  * If so, should we make pages swipe-able here so you can move between pages and change their colors quickly?

Let's address these and update the ticket.


Thoughts?

**Comment by thisandagain** [comment]
Removing from critical path for 1.0.0

**Comment by xmatthewx** [comment]
@flukeout suggests that we choose a random color if it's the first page of a new project. If adding second page, default is last-set page background color.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/36"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/36.
Please don't comment on it here.
