### ISSUE TITLE
Remote tests - synthesize and report feedback

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1548]
see fledgling testing plan #1527

**Comment by flukeout** [comment]
Recommendations based on usertesting.com so far: 

**Play Mode**
* [ ] Add pinch gestures for zooming in and out of the map modes
* [ ] Some neighbor tiles aren't very noticeable in semi-zoom mode
* [ ] Limit panning the map so you can't pan totally away from the content and lose your space (need to define UX for this)
* [ ] Resolve android Back Button functionality - Specifically, make it zoom out of zoomed in views #1545 
* [ ] Entering and exiting Zen Mode wasn't totally clear, user thought it was part of a specific project rather than a mode all projects had access to

**Comment by xmatthewx** [comment]
@flukeout - thanks for all the details. 

It seems like these observations will impact how we'd approach pinch-to-zoom and future improvements to discover previews.  What if each discover card had some indication of the map or the size of the project? Page count?

While it's fresh in your mind -- is there anyway you'd adjust the script for future tests?

**Comment by flukeout** [comment]
**Discover View**
Either a page count or some way to reveal a mini-map might be a good way to suggest that these are more than just photos. I can UX something up. I think another improvement is to convey that these things were created in this app, rather than pinned or favorited things from other places.

**Script Updates**
Other than some minor wording updates, the main thing I want to improve is framing the Discover view a little better (relates to the point made above). It would be good to frame that view as a bunch of content recently made *in this tool* by *people like you*! That might get some different reactions.

**Comment by LauraReynal** [comment]
@lauraReynal :sunglasses:

**Comment by xmatthewx** [comment]
keeping open during beta 1/2 to continue dialog

**Comment by xmatthewx** [comment]
@flukeout - should we keep this open and bump it to the next milestone? Or, is most of this either addressed or no longer relevant?

**Comment by flukeout** [comment]
@xmatthewx I'll review it today and carry over whatever is left that still feels relevant.

**Comment by xmatthewx** [comment]
Closing as most of this is filed, out of date, or resolved.
