### ISSUE TITLE
Create localization strategy

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#1599]
* Started info gathering process here: https://etherpad.mozilla.org/localizing-webmaker
* Need to finalize and file follow-up tickets

cc @HPaulJohnson

**Comment by secretrobotron** [comment]
Launch playbook will be an important piece of this here. One of the roles identified is for Localization/QA.

**Comment by secretrobotron** [comment]
#### What needs to be localized?
* Webmaker App
* Webmaker.org
* Login (id.webmaker.org)
* Emails (ExactTarget?)
* Push notifications (ExactTarget?)
* Snippet
* Social media ??
* Promotional Kit

@k88hudson can we try to write out some technical needs for each one of these? Going as far as picking which system/community tool we'd use to do the localization (e.g. transifex).

**Comment by k88hudson** [comment]
@secretrobotron 

1. Webmaker app - Any platform would be fine as long as it supports Android XML (Transifex does). I would recommend localizing everything in the same place for Android, and passing the appropriate strings that are needed via the JS/Java binding.
2. Webmaker.org - Is this the desktop app, or do you mean the landing page for webmaker.app? 
3. Login - I would recommend looking into a React-ready solution, such as https://github.com/yahoo/react-intl. Transifex or whatever platform we prefer should be fine.
4. Emails: Honestly I don't know much about ExactTarget, would have to look into this first. For v1 I would recommend not localizing emails.
5. Same as Emails
6. Snippet: Tech here depends on the specific implementation (it would likely be a build step, not at runtime). It's very important in this case to have a good review process/reliable translators. 
7. Social media - this would need to be done on an individual basis, with "owners" for each localized social media account. I would recommend not pursing this until we have a content strategy for individual market
8. Promotional kit - also important to have a good review process and reliable translators

Overall, I would recommend the following:

* We should plan for string freeze dates on any projects that need to be localized for launch
* We should identify designated reviewers for each language and have a QA period to run through each translation (this should be built into pre-launch/QA cycles)
* We should try to have a good understanding of which languages are important for launch, and a strategy to do outreach/reward and thank contributors for participating in localization cycles
* We should try to use existing tech for i18n where possible instead of inventing our own, as long as it fulfills our requirements

**Comment by k88hudson** [comment]
An example of a QA/review cycle would be as follows:

* someone finds/designates reviewers for languages X,Y, Z, contacts them, and explains the process
* when a QA cycle begins, someone sends out a link to the release candidate of the app, as well as a copy of a manual QA script and a link where to file localization bugs
* reviewer goes through the app, filing bugs with incorrect strings and includes corrections
* corrections are input into the system
