### ISSUE TITLE
[MIGRATED] Android - Update navigation / activity control styles to match spec

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1604]
@vazquez can you add some references and implementation notes for the navigation bar(s) in here? I think we've got four distinct navigation control states:

- Discover / make
- Map
- Tinker
- Everything else (default?)

Anything I'm missing? /cc @xmatthewx

**Comment by vazquez** [comment]
##### Map View Navigation Bar

![screenshot 2015-04-29 13 44 27](https://cloud.githubusercontent.com/assets/1119821/7397384/f3f71e42-ee75-11e4-8db5-0efe408f88e3.png)

The most distinct aspect of the Map View navigation bar is it's 'back' icon. Instead of showing the standard &#8592; icon, we are displaying the 'exit' icon. When in Map View, if they user presses this icon, they exit back to Discover, Make or Profile Views.

The vertical ellipsis reveals more actions, as per Google's Material Design guidelines.

![screenshot 2015-04-29 14 30 59](https://cloud.githubusercontent.com/assets/1119821/7398350/7802037c-ee7c-11e4-9aad-7c3b4d61d785.png)

---

##### Discover/Make Tab Bar Navigation

![screenshot 2015-04-29 13 53 14](https://cloud.githubusercontent.com/assets/1119821/7397598/84baef5c-ee77-11e4-96b6-1cadace34f6a.png)

The Discover/Make View features a Tab Bar as specified in [Google's Material Design](http://www.google.com/design/spec/components/tabs.html). A tab bar provides the affordance for displaying grouped content. When a view is active, a bar of colour is displayed underneath it.

---

##### Element Options Navigation (Colour Options, Text Options, Image Options, Button Options)

![screenshot 2015-04-29 14 06 56](https://cloud.githubusercontent.com/assets/1119821/7397855/1ebda7b0-ee79-11e4-862b-e2af54f5f739.png)

When a user adds an Element to a Page such as Text, Image, or Button, they are able to edit their specific options. Using a [Parent to Child](http://www.google.com/design/spec/patterns/navigational-transitions.html#navigational-transitions-parent-to-child) navigation transition, we reveal the Element Options Screen. This navigation bar features a checkmark on the right hand side.

---

##### Tinker Mode Navigation Bar

![screenshot 2015-04-29 14 19 44](https://cloud.githubusercontent.com/assets/1119821/7398110/e349a0ba-ee7a-11e4-8d25-564e67432066.png)

When a user taps on the Tinker Mode button they access Tinker Mode :zap:. Tinker Mode is accessed using a [Sibling to Sibling](http://www.google.com/design/spec/patterns/navigational-transitions.html#navigational-transitions-sibling-to-sibling) navigation transition. The unique aspect of this screen is the fact that the back arrow *also* acts as a way to commit the changes the user might have done. So: back arrow === save.

**Comment by xmatthewx** [comment]
Excellent summary @vazquez 
 - Discover-Project is a parent-child relationship as well.  
 - Issue #1545 outlines back button behavior if that's helpful.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/46"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/46.
Please don't comment on it here.
