### ISSUE TITLE
[MIGRATED] Build color picker for tinker mode

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1710]
Discussion in #1528

**Comment by xmatthewx** [comment]
@vazquez - post final artwork and notes here

**Comment by vazquez** [comment]
### Design Notes

*Scenario:* When adding a colour to the border, the user taps on Tinker mode to set a custom colour.

![screenshot 2015-05-11 11 03 08](https://cloud.githubusercontent.com/assets/1119821/7567854/59bd3b20-f7cd-11e4-9b5c-0c7b9fce8718.png)

#### Simple Colour Tinker Mode

*Refer to Tinker Mode Navigation Bar in #1604 for navigation specifications.*

The user will land in the Simple colour selection mode. This option gives the user a colour wheel to > create their custom colour value. The [HWB colour wheel](http://fettblog.eu/hwb-colors/) (Hue, Whiteness, Blackness) provides for a more [intuitive colour selection](http://alvyray.com/Papers/CG/HWB_JGTv208.pdf).

> The (H)ue of the HWB model is exactly that of the HSV and HSL models. Changing the hue corresponds to moving around the familiar color circle seen in paint stores.

> The use of HWB is simply described to even the newest user: Choose a hue. Darken it with blackness. Lighten it with whiteness. More carefully stated it is this: Choose a hue. Blacken it, or a tint of it, with blackness. Whiten it, or a shade of it, with whiteness. 

> Alvy Ray Smith and Eric Ray Lyons

##### Notes

1. The Page background colour appears in the Preview.
2. The user can tap on the circle to select a (H)ue. Then, the user can modify the (W)hiteness or (B)lackness of the Hue by tapping on the inside of the triangle.
3. As the user taps on the Hue circle, the Triangle moves with the Hue selection.
4. A Hex value of the colour displays at the top. A real-time colour preview displays in a square.
5. The user can also modify the alpha value of the colour by sliding the Transparency value. *Important:* If the user modifies this value, the Hex value at the top (number 4)) turns to an RGBA value. 

![new image picker](https://cloud.githubusercontent.com/assets/1119821/7568778/b460189a-f7d2-11e4-9a50-53f023fb724f.png)

#### Advanced Colour Tinker Mode

Advanced Tinker Mode includes a range of sliders comprising of the RGBA values.

##### Notes

1. The same colour value and colour preview displays. The only difference is that instead of displaying a Hex value, the interface now displays an RGBA value.

![border colour tinker mode 2](https://cloud.githubusercontent.com/assets/1119821/7568963/c40ce916-f7d3-11e4-9969-b7dc39da6421.png)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/68"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/68.
Please don't comment on it here.
