### ISSUE TITLE
[MIGRATED] Create Project button is too picky about what kinds of taps it likes

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1932]
It's very easy to tap the Create Project button on the Make view with no effect. It seems like it only likes very quick taps, holding down your finger for even a short period of time before releasing makes the button unresponsive.

Let's not set a limit (or at least not as aggressive) to how fast the tap needs to be, especially because the "pressed state" on the button suggests that you're using it correctly even if holding it for a long time.

For reference, the Make and Discover tabs can be tapped and held for a long time before releasing your finger, and they still work.

**Comment by k88hudson** [comment]
Honestly, there is nothing on this button that could possibly make it respond differently from the others....

...however, I think this issue is appearing tto happing because we don't have a blocking loading state on creating a new project, which is also causing https://github.com/mozilla/webmaker-android/issues/1930

**Comment by flukeout** [comment]
@k88hudson There is definitely a difference between how some of the UI / buttons in the app work. For example, try long-pressing the 'back arrow' in the header in the Project Editor "works". Long-pressing the "Create Project" button doesn't work. You can't reproduce this?

**Comment by k88hudson** [comment]
Wow, you're right. Looks like the default behaviour of buttons/anything clickable in Chrome is not to trigger a "click"/"tap" if you hold down your finger for a long time. I'm guessing this is because it would be impossible otherwise to detect a "taphold" gesture.

The back buttons at the top are Android, which do not appear to have this behaviour.

It will be a very significant amount of work to override the default behaviour of onClick for all buttons/interactive elements, are you sure this is critical to the user experience?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/128"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/128.
Please don't comment on it here.
