### ISSUE TITLE
TypeError on PanZoom when loading a project

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#2009]
I have hit an error a few times in which I load a project (from Discover) and the project fails to load. I'm seeing this in the console:
```bash
[INFO:CONSOLE(167)] "Uncaught TypeError: Cannot read property 'panzoom' of undefined", source: file:///android_asset/www/js/project.bundle.js (167)
```

The line in question:
```js
matrix = matrix || this.$boundingEl.panzoom("getMatrix");
```

**Comment by thisandagain** [comment]
If I go back and try again it will often work. I'm guessing we have some sort of race condition.

**Comment by Pomax** [comment]
we do, because we're not respecting function calls with respect to React lifecycles. `load` gets called before initial render, so there is no `this.$boundingEl`, and things break. The proper solution here would be to make sure we're not doing anything that relies on having DOM nodes until after the component mounted and `this.refs` exist. I'm going to have to in part blame jQuery here: if this code worked on `this.refs` and even `this.getDOMNode()` results, React would have been able to signal that we were trying to access things that don't exist at the moment we try to access them.

This highlights a potential problem with how we've thought about handling state loading: state loading should kick in first, then the component needs to render, then we can start doing things that rely on the component having a physical representation (e.g. DOM nodes) for tapping into.

**Comment by Pomax** [comment]
We backed out the panzoom patch, so this issue is closed, but I can't find the original bug that this PR addressed for reopning.

**Comment by Pomax** [comment]
Original bug: https://github.com/mozilla/webmaker-android/issues/1697
