### ISSUE TITLE
First time edit of an element's text duplicates the text on the very first Android keystroke

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2050]
1. Add a text element
2. Click on the pencil to edit it
3. Quickly, tap on the text to start editing the content and start deleting (backspace)

The result is usually something like, "Hello worldworl".

**Comment by xmatthewx** [comment]
This bug made it very difficult for me to build some fairly basic content. It feels like aggressive auto-correct. Maybe there's a delay switching between the element and the temp input field?

**Comment by secretrobotron** [comment]
I have a feeling that the method we use to fetch data from the API is to blame (cc @k88hudson).

**Comment by Pomax** [comment]
confirmed as still happening using listed STR

**Comment by Pomax** [comment]
Even simply hitting "edit", then waiting near-forever, and having backspace be the first keypress will duplicate the string, so that should make it easier to track down.

**Comment by Pomax** [comment]
The Android chain of events when using the software keyboard is drastically different from the normal browser, due to the software keyboard being able to generate huge strings with a single "key" press. As such, key events from the Android keyboard don't respect the concept of keycodes but so something more opaque.

In the browser, typing yields keydown/change/keyup as KeyboardEvent, Input, KeyboardEvent. In Android, instead we see a KeyboardEvent, "Event", KeyboardEvent. 

The only solution  I can come up with here is to do a check on what's being changed on "first update", and force-replace it's entirely wrong content by substring replacing the initial value out of the duplicated resultant string. **This is ugly**, but will work, and is really the only thing I can think of as solving our problem now, rather than after a week of Android code diving.
