### ISSUE TITLE
Synchronous updates can't block view changes

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#2053]
Relying on API updates to finish before allowing subsequent UI interactions works in some cases, but the loading state does *not* block the back button;

Because of this, there is sometimes a case where before an element update to the API is completed, the user presses "back" and a new page loads with old data.

This is what is causing most of the strange behaviour with things not updating when switching between views.

In order to fix this from a temporary standpoint, we could do a couple of things:

* Delay the loading of a new page if an API update is in progress
* Make updates more granular (e.g. in the Element Editor, update on `touchend` or `change` rather than when the view becomes paused.

**Comment by k88hudson** [comment]
cc @Pomax @thisandagain @gvn

**Comment by Pomax** [comment]
I want to push farther and say "not offline-first was the wrong decision", so that users would explicitly have to push the "yeah store this in the cloud now that I am ready to connect to the internet and pay all the money this will cost me" =)

Although realistically, at the very least the user should not be confronted with what we "need" to do to remote-cache what they're doing, so screen changes should be instant, with synch-up from what they were doing in the previous view possible coming in later (either as an update flash, or by blocking render with the knightrider spinner).
