### ISSUE TITLE
redo the button disabling by taking out the setTimeout

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-android#2074]
https://github.com/mozilla/webmaker-android/pull/2049 accidentally landed some code that makes sense in traditional HTML, but should never feature in React code. The button disabling should be immediate upon an addElement call, and the subsequent button enabling should be triggered by the element having been added, not via a timeout.

**Comment by errietta** [comment]
@Pomax can has mentoring?

**Comment by thisandagain** [comment]
Hey @Pomax, 
If I'm reading this correctly, it looks like @errietta is using the timeout not to wait for the element being added, but rather to wait for the CSS transition to complete. As otherwise the user could add another element in-between the time the element is added and the overlay / buttons transition off-screen (which takes 200ms). It looks like we could use the [ReactCSSTransitionGroup](https://facebook.github.io/react/docs/animation.html#high-level-api-reactcsstransitiongroup) to do what you are describing ... is that what you are thinking?

**Comment by thisandagain** [comment]
Follow-up: @errietta is going to take another crack at it using the React animation APIs.

**Comment by errietta** [comment]
sir @Pomax :3
