### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2112]
My username and password work on the Teach site. Webmaker app reports: "looks like there might be a problem with your username or password"

@vazquez was able to repeat

**Comment by k88hudson** [comment]
@xmatthewx @vazquez if you are talking about teach.webmaker.org, your credentials will not work on webmaker app since teach uses a production login server and webmaker-app is linked to the stating login server. The corresponding teach site would be https://teach.mofostaging.net/.

Can you confirm if this is the issue?

**Comment by xmatthewx** [comment]
Ah, ok. Question: will we use the staging server while Beta is in the play store? If so, can we migrate new users to the production server?
