### ISSUE TITLE
[MIGRATED] Replace document.body.style.overflowY = 'hidden'; with a better strategy

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#2122]
Right now we're using 

```
document.body.style.overflowY = 'hidden';
```

to block pull-to-refresh on a page, let's find a better way to do this (through an API on the root component or something, for example)

**Comment by Pomax** [comment]
there is a better way that we already make use of for touchhandler.js - Android looks at whether it's being instructed to event.preventDefault() as *very first call* in the event handler. If it's there, Android gestures don't kick in and you can do whatever you like. If it's not there, or it's not the first call/extraction on the event, default Android gestures will keep working as normal.

So instead of setting style, we can tactically add `preventDefault` calls where needed.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/175"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/175.
Please don't comment on it here.
