### ISSUE TITLE
add background color & border to text

### ISSUE THREAD

**Issue by ariefbayu** [mozilla/webmaker-android#2225]
It would be better if user could set background color to something like comic bubble. The idea is, we try to market webmaker android to comic community and let them create multiple ending story, something like the good old goosebump novel book :)

**Comment by ariestiyansyah** [comment]
@ariefbayu ah interesting, I agree with arief idea we can try market the webmaker to comic community. Webmaker android with full of comic in timeline.

**Comment by xmatthewx** [comment]
Thanks @ariefbayu and @ariestiyansyah. We talked about background color for text, since this will make it easier to put text over photos. The feature will need to wait while we complete more critical parts of the app first. Follow this topic here: https://github.com/mozilla/webmaker-android/issues/1674
