### ISSUE TITLE
[MIGRATED] UI - 404 for Projects and Pages

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2232]
Let's design this for both mobile app and responsive desktop player. 
 - Project 404 - Scenario: share link leads to a non-existent project
 - Page 404 - Scenario: in player, user follow a link to non-existent page

related to #2230

**Comment by vazquez** [comment]
### Project 404

I have a couple of options with a few variations.

#### Option A

- A notice bar that appears when you land on a non-existent project. We redirect to Discover view and show the notice as an info bar.
- This notice is not fixed, it will scroll with the page.

![discover view share 404](https://cloud.githubusercontent.com/assets/1119821/8185927/197474f2-1415-11e5-9b83-ac59d3be5a13.png)  

---

![discover view share 404 copy 3](https://cloud.githubusercontent.com/assets/1119821/8185932/20c205c6-1415-11e5-8a6d-1f58c4ee2c7b.png)

---

![discover view share 404 copy 2](https://cloud.githubusercontent.com/assets/1119821/8185937/262d42fa-1415-11e5-859a-25dd5753442d.png)

---

#### Option B

- Instead of a notice bar, we display a message on the page background.
- This approach can alleviate the colour tension that happens when you place a notice bar close to the segmented header (Version A)
- Message would also scroll with the page.

![discover view share 404 copy](https://cloud.githubusercontent.com/assets/1119821/8186007/8f11249e-1415-11e5-8a45-0de4f6171865.png)


cc @xmatthewx @thisandagain @cassiemc  @flukeout

**Comment by xmatthewx** [comment]
We can tackle this post-Whistler.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/192"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/192.
Please don't comment on it here.
