### ISSUE TITLE
[MIGRATED] Reorder projects

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-android#2267]
I would love to have the ability to reorder my projects 
- so the one I prefer to be the first
- the latest I am working on should the the first to reach 
- other possibilities

**Comment by ioana-chiorean** [comment]
I think thi is the same or related to https://github.com/mozilla/webmaker-android/issues/2138

**Comment by xmatthewx** [comment]
Thanks for the feedback @ioana-chiorean. In "Discover" we sort by `date created`. In "Make" it probably makes sense to sort by `date updated`, so that ongoing active projects remain at the top and easier to find. 

We might not be able to implement this right now, but it's good feedback for when we start to think about building up profiles later this year.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/204"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/204.
Please don't comment on it here.
