### ISSUE TITLE
Bug: Inconsistancy thumbnails

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-android#2275]
After ding some edits I saw the thumbnail of the project will change o represent the main page. 
After some more edits it disappears and displays no image. 
It gets frustrating as u can not set a default image/thumbnail

<img src="https://cloud.githubusercontent.com/assets/1391451/8220654/46c4abee-155e-11e5-96ab-376392eec311.jpg" width="300">

<img src="https://cloud.githubusercontent.com/assets/1391451/8220655/46c4b1e8-155e-11e5-8c68-464350f25e6a.jpg" width="300">

**Comment by ryanw-se** [comment]
Although I definitely agree the thumbnail does need some work, I think a better solution would be to provide a zoomed out version of the actual project, so you can get a preview of what you're interested in clicking on.

**Comment by ioana-chiorean** [comment]
agree - I think in a form is what we get now but the problem is now that it disappears after some time

**Comment by xmatthewx** [comment]
Thumbnails have a few known bugs that should be fixed in our next release. Please post new issues if you continue to see problems after that release comes out. 

After the bugs are squashed, we might see that people learn how to use the automatic thumbnails more intentionally. If we don't, we can discuss other options later on this summer.
