### ISSUE TITLE
Change logos and text on Transifex

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2285]
The branding on Transifex still represents webmaker.org (as opposed to Mozilla or the app). We should figure out what to put there instead.

**Comment by xmatthewx** [comment]
tracking here: https://github.com/mozilla/webmaker-launch/issues/38

**Comment by xmatthewx** [comment]
@alicoding - can you update this? Logo is available here: https://drive.google.com/open?id=0B2qu3ExKWIlvckVJNDI2TWdERTQ

**Comment by alicoding** [comment]
I just updated the logo and it doesn't look good there with text beside the logo at all since the size of the logo is very small on Transifex 
<img width="1132" alt="screen shot 2015-07-07 at 3 48 25 am" src="https://cloud.githubusercontent.com/assets/4368149/8541309/2623d638-245b-11e5-9d59-207e74b4411e.png">

**Comment by secretrobotron** [comment]
This one might work better. SVG, just the logo: https://drive.google.com/open?id=0B-7F6kqkuFwdNHRld3pTcDl4VDQ

**Comment by alicoding** [comment]
Much better 
<img width="1138" alt="screen shot 2015-07-07 at 11 20 51 am" src="https://cloud.githubusercontent.com/assets/4368149/8549734/618e71da-249a-11e5-83b8-b9f13b89335d.png">
