### ISSUE TITLE
[MIGRATED] Add phone features & capabilities 

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2351]
* Send SMS
* Place a call
* ...
* Rename a contact in your phone book?
* Import your phone settings in an JSON file to a project

**Comment by thisandagain** [comment]
I'm not sure if I agree with this given that we want partity across desktop and mobile.

**Comment by ryanw-se** [comment]
Maybe if we implemented this as sort of a "if feature function", here's a quick example of how I think this could work. If we had the feature, place a call if the user is on a device that has phone capabilities it should place the call, otherwise it should display a phone number or something of that sort.

You could enable or disable this capability to fast track the response on a mobile device, so really the only change is that on devices that support it, you would get a quicker route to the end result (making the phone call).

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/257"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/257.
Please don't comment on it here.
