### ISSUE TITLE
[MIGRATED] Text gets erased when editing 

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2352]
Steps to reproduce
* Add a text element
* Edit the text to something
* Go back to the map view
* Edit the text
* Place the text edit cursor in the middle of the word
* Add a letter
* The existing text is erased completely, and only your typed character remains

**Comment by Pomax** [comment]
This might be related to the text doubling - in order to get the cursor at the end of the word if you do a normal tap, we form a selection, and then supposedly unselect again. However, I've seen the selection do rather creative "this is not what we expected" things, which this sounds an example of: despite "unselecting", Android keeps the selection around, and when you tap, selections should get replaced, so it does.

**Comment by xmatthewx** [comment]
I've noticed bugs while composing text using Facebook in Chrome on Android. Not this specifically, but we should keep an eye out for React issues.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/258"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/258.
Please don't comment on it here.
